export const oldProjects = [
  {
    title: "城市之光",
    project_code: "project01",
    cover_image: "project01.png",
    year_cover_image: "year_pro01.png",
    address: "新北市三重區三信路180號",
    land_size: "289.34坪",
    house_size: "37.45-38.2坪",
    build_floor: "10F+B2F",
    build_count: "27戶+28車",
    build_design: "巨仲建築師事務所",
    build_create: "振城營造股份有限公司",
    build_openspace: "",
    open_year: "2007",
    type: "old",
    meta_title: "",
    meta_description: "",
  },
  {
    title: "城市遠見",
    project_code: "project02",
    cover_image: "project02.png",
    year_cover_image: "year_pro02.png",
    address: "新北市三重區集智街8號",
    land_size: "300.25坪",
    house_size: "30.44-51.74坪",
    build_floor: "11F+B2F",
    build_count: "30戶+30車",
    build_design: "巨仲建築師事務所",
    build_create: "振城營造股份有限公司",
    build_openspace: "",
    open_year: "2009",
    type: "old",
    meta_title: "",
    meta_description: "",
  },
  {
    title: "集英堡一期",
    project_code: "project03",
    cover_image: "project03.png",
    year_cover_image: "year_pro03.png",
    address: "新北市三重區三德街30號",
    land_size: "550.69坪",
    house_size: "30.51-83.24坪",
    build_floor: "13F+B2F",
    build_count: "47戶+51車",
    build_design: "巨仲建築師事務所",
    build_create: "振城營造股份有限公司",
    build_openspace: "",
    open_year: "2007",
    type: "old",
    meta_title: "",
    meta_description: "",
  },
  {
    title: "集英堡二期",
    project_code: "project04",
    cover_image: "project04.png",
    year_cover_image: "year_pro04.png",
    address: "新北市三重區集智街8號",
    land_size: "566.24坪",
    house_size: "28.91-37.62坪",
    build_floor: "12F+B2F",
    build_count: "59戶+59車",
    build_design: "巨仲建築師事務所",
    build_create: "振城營造股份有限公司",
    build_openspace: "",
    open_year: "2008",
    type: "old",
    meta_title: "",
    meta_description: "",
  },
  {
    title: "集英堡三期",
    project_code: "project05",
    cover_image: "project05.png",
    year_cover_image: "year_pro05.png",
    address: "新北市三重區集仁街158號",
    land_size: "901.60坪",
    house_size: "37-67坪",
    build_floor: "13F+B2F",
    build_count: "94戶+94車",
    build_design: "吳非士建築師事務所",
    build_create: "振城營造股份有限公司",
    build_openspace: "",
    open_year: "2011",
    type: "old",
    meta_title: "",
    meta_description: "",
  },
  {
    title: "集英堡五期",
    project_code: "project06",
    cover_image: "project06.png",
    year_cover_image: "year_pro06.png",
    address: "新北市三重區吉祥街68號",
    land_size: "243.89坪",
    house_size: "42~70坪",
    build_floor: "11F+B3F",
    build_count: "30戶+30車",
    build_design: "吳非士建築師事務所",
    build_create: "振城營造股份有限公司",
    build_openspace: "",
    open_year: "2013",
    type: "old",
    meta_title: "",
    meta_description: "",
  },
  {
    title: "集英堡六期",
    project_code: "project07",
    cover_image: "project07.png",
    year_cover_image: "year_pro07.png",
    address: "新北市三重區集英路17號",
    land_size: "442.88坪",
    house_size: "42.59-66.72坪",
    build_floor: "11F+B2F",
    build_count: "40戶+40車",
    build_design: "巨仲建築師事務所",
    build_create: "振城營造股份有限公司",
    build_openspace: "",
    open_year: "2014",
    type: "old",
    meta_title: "",
    meta_description: "",
  },
  {
    title: "集英富琚",
    project_code: "project08",
    cover_image: "project08.png",
    year_cover_image: "year_pro08.png",
    address: "新北市三重區集賢路189號",
    land_size: "478.33坪",
    house_size: "34-48坪",
    build_floor: "13F+B4F",
    build_count: "52戶+56車",
    build_design: "吳非士建築師事務所",
    build_create: "振城營造股份有限公司",
    build_openspace: "映荷空間設計",
    open_year: "2022",
    type: "hot",
    albums: [
      "08/p01.png",
      "08/p02.png",
      "08/p03.png",
      "08/p04.png",
      "08/p05.png",
      "08/p06.png",
      "08/p07.png",
      "08/p08.png",
      "08/p09.png",
      "08/p10.png",
      "08/p11.png",
      "08/p12.png",
      "08/p13.png",
    ],
    meta_title:
      "【新北市三重區建案】集英富琚:吳非士設計，振城營造打造，景觀生活 享受 - 三重區建案集英富琚|祥富龍/祥旭龍|新北市三重區新建案 2022年 矚目推出",
    meta_description:
      "【集英富琚】位於新北市三重區集賢路189號，這個獨特的建案擁有478.3 3坪基地面積，提供34-48坪的精緻住宅。該建案共規劃13層樓高，附帶4層地下室， 共有52戶住宅單位和56個停車位。由著名的吳非士建築師事務所設計，並由振城營造 股份有限公司施工建造。集英富琚的公共空間由映荷空間設計操刀，結合時尚與實 用。該建案於2022年推出，成為三重區的矚目新寵。探索集英富琚，感受品質生活的 魅力。",
  },
  {
    title: "喜福匯No3",
    project_code: "project11",
    cover_image: "project11.png",
    year_cover_image: "year_pro11.png",
    address: "新北市蘆洲區仁愛街90號",
    land_size: "229.30坪",
    house_size: "25.81-55.77坪",
    build_floor: "10F+B2F",
    build_count: "19戶+19車",
    build_design: "陳朱平建築師事務所",
    build_create: "全國營造股份有限公司",
    build_openspace: "映荷空間設計",
    open_year: "2017",
    type: "hot",
    albums: ["11/p01.png", "11/p02.png", "11/p03.png"],
    meta_title: "",
    meta_description: "",
  },
  {
    title: "喜福匯No2",
    project_code: "project10",
    cover_image: "project10.png",
    year_cover_image: "year_pro10.png",
    address: "新北市蘆洲區三民路501號",
    land_size: "254.24坪",
    house_size: "28.11-52.14坪",
    build_floor: "11F+B2F",
    build_count: "32戶+29車",
    build_design: "吳非士建築師事務所",
    build_create: "振城營造股份有限公司",
    build_openspace: "映荷空間設計",
    open_year: "2017",
    type: "hot",
    meta_title: "",
    meta_description: "",
  },
  {
    title: "喜福匯No1",
    project_code: "project09",
    cover_image: "project09.png",
    year_cover_image: "year_pro09.png",
    address: "新北市蘆洲區長樂路166號",
    land_size: "318.50坪",
    house_size: "30.15-59.82坪",
    build_floor: "12F+B2F",
    build_count: "33戶+36車",
    build_design: "吳非士建築師事務所",
    build_create: "振城營造股份有限公司",
    build_openspace: "映荷空間設計",
    open_year: "2017",
    type: "old",
    meta_title: "",
    meta_description: "",
  },
  {
    title: "喜福匯No5",
    project_code: "project12",
    cover_image: "project12.png",
    year_cover_image: "year_pro12.png",
    address: "新北市三重區成功一街31號",
    land_size: "488.36坪",
    house_size: "22.36-47.17坪",
    build_floor: "17F+B4F",
    build_count: "77戶+77車",
    build_design: "吳非士建築師事務所",
    build_create: "振城營造股份有限公司",
    build_openspace: "映荷空間設計",
    open_year: "2020",
    type: "hot",
    albums: [
      "12/p01.png",
      "12/p02.png",
      "12/p03.png",
      "12/p04.png",
      "12/p05.png",
      "12/p06.png",
      "12/p07.png",
    ],
    meta_title: "",
    meta_description: "",
  },
  {
    title: "喜福匯No6",
    cover_image: "project13.png",
    project_code: "project13",
    images: ["new_work02_1.png", "new_work02_2.png"],
    map_image: "new_work02_map.png",
    address: "新北市蘆洲區三民路",
    land_size: "492.80坪",
    house_size: "25-39坪",
    build_floor: "14F+B3F",
    build_count: "58戶+72車",
    build_design: "吳非士建築師事務所",
    build_create: "全國營造股份有限公司",
    build_openspace: "",
    build_env: "",
    start_date: "110-10-27",
    open_year: "2023",
    type: "hot",
    meta_title:
      "蘆洲三民路喜福匯No6全新建案|祥富龍/祥旭龍|新北市蘆洲區 新建案 2023年矚目推出",
    meta_description:
      "喜福匯No6 - 蘆洲區三民路優質新建案，擁有絕佳地理位置、精緻建築設 計及完善交通，位於新北市蘆洲區三民路的喜福匯No6新建案，提供您在都會區中的 綠意居所。基地面積492.80坪，規劃有25-39坪不等的精緻戶型，共14樓及地下3層。 喜福匯No6提供58戶住宅單位及72個停車位，可滿足居住者的不同需求。由吳非士建 築師事務所設計，全國營造股份有限公司擔任施工營造，保證品質與安全。喜福匯No 6於2023年推出，是蘆洲區最新的優質建案。",
  },
  {
    type: "hot",
    open_year: "2025",
    title: "福美富琚",
    cover_image: "project14.png",
    project_code: "project14",
    images: ["new_work01_1.png", "new_work01_2.png"],
    map_image: "new_work01_map2.png",
    address: "新北市新莊區福前街135巷1號",
    land_size: "609.92坪",
    house_size: "20-35坪",
    build_floor: "13F+B4F",
    build_count: "91戶+100車",
    build_design: "吳非士建築師事務所",
    build_create: "全國營造股份有限公司",
    build_openspace: "澄統綠建築設計、境業設計工程公司(陳志宏建築師事務所)",
    build_env: "境業設計工程公司",
    start_date: "2022-10-25",
    meta_title: "",
    meta_description: "",
  },
];

export const newProjects = [
  {
    title: "福美富琚",
    project_code: "new_work01",
    images: ["new_work01_1.png", "new_work01_2.png"],
    map_image: "new_work01_map2.png",
    address: "新北市新莊區福前街135巷1號",
    land_size: "609.92坪",
    house_size: "20-35坪",
    build_floor: "13F+B4F",
    build_count: "91戶+100車",
    build_design: "吳非士建築師事務所",
    build_create: "全國營造股份有限公司",
    build_openspace: "澄統綠建築設計、境業設計工程公司(陳志宏建築師事務所)",
    build_env: "境業設計工程公司",
    start_date: "2022-10-25",
    meta_title: "",
    meta_description: "",
  },
  {
    title: "喜福匯No6",
    project_code: "new_work02",
    images: ["new_work02_1.png", "new_work02_2.png"],
    map_image: "new_work02_map.png",
    address: "新北市蘆洲區三民路",
    land_size: "492.80坪",
    house_size: "25-39坪",
    build_floor: "14F+B3F",
    build_count: "58戶+72車",
    build_design: "吳非士建築師事務所",
    build_create: "全國營造股份有限公司",
    build_openspace: "",
    build_env: "",
    start_date: "2021-10-27",
    meta_title: "",
    meta_description: "",
  },
];

export const hotProjects = [];
export const urbanDevProjects = [
  {
    title: "敬請期待",
    project_code: "project01",
    cover_image: "project01.png",
  },
];
